name: menu-training-tracker-api
region: nyc
services:
- name: api
  github:
    repo: esolow/menu_training_tracker
    branch: main
    deploy_on_push: true
  source_dir: server
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: PORT
    value: "8080"
  - key: JWT_SECRET
    value: "CHANGE_THIS_TO_A_SECURE_RANDOM_STRING"
    scope: RUN_TIME
    type: SECRET
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3

